# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://sizhuxuan.github.io
date_format: 'ordinal'
title: 苏子的客人
subtitle: '不积跬步，无以至千里；不积小流，无以成江海'
description: 'description'
keywords: 前端
timezone: Asia/Shanghai
encoding: 'utf-8'
side_bar_repo_limit: 5
repository: sizhuxuan/sizhuxuan.github.io
repository_branch: 'master'
repository_images_branch: 'images'
# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: true
# 组件配置
components:
    # 分享
    share:
        enabled: false
    # 不蒜子访问统计
    busuanzi:
        enabled: false
        start_date: 2020-05-03
# 压缩页面内容
compress_html:
    clippings: all
    comments: ['<!--', '-->']
# 文章字数统计
word_count:
    enabled: true

# 深色模式（简单版），可选值：automatic 跟随系统；usercontrol 用户控制；none 不需要。  default: none;
dark_mode: usercontrol

# 代码高亮风格，支持的 theme 列表见 https://github.com/mzlogin/rouge-themes
highlighter: rouge
highlight_theme: github

# ---------------- #
#      Author      #
# ---------------- #
author: sizhuxuan
organization:
organization_url:
github_username: sizhuxuan
location: shanghai, China
email: zhaotaoworkspace@gmail.com
since_date: 2016

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
    - href: /
      label: 首页

    - href: /categories/
      label: 分类

    #   -
    #     href: /archives/
    #     label: 归档

    #   -
    #     href: /open-source/
    #     label: 开源

    - href: /wiki/
      label: 维基

    - href: /links/
      label: 链接

    - href: /about/
      label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
    #     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
# 备注，provider选择哪个，相应的就要配置下面其中一个
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
comments_provider: gitalk
# https://disqus.com 文档
disqus:
    username:

# https://imsun.net/posts/gitment-introduction/ 文档
# gitment:
#     owner:
#     repo:
#     oauth:
#         client_id:
#         client_secret:

# https://github.com/gitalk/gitalk#install 文档
# gitalk:
#     owner:
#     repo:
#     clientID:
#     clientSecret:
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus: false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10
# ---------------- #
#      Google      #
# ---------------- #
# google:
#     analytics_id: UA-80669434-1
#     adsense:
#         footer: true
#         sidebar: true
#         content_header: true
#         content_footer: false
